/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/kosik`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/mapa`; params?: Router.UnknownInputParams; } | { pathname: `/mapa/context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/pestitele`; params?: Router.UnknownInputParams; } | { pathname: `/pestitele/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/kosik`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/context/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/mapa`; params?: Router.UnknownOutputParams; } | { pathname: `/mapa/context/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/pestitele`; params?: Router.UnknownOutputParams; } | { pathname: `/pestitele/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/kosik${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/context/CartContext${`?${string}` | `#${string}` | ''}` | `/mapa${`?${string}` | `#${string}` | ''}` | `/mapa/context/CartContext${`?${string}` | `#${string}` | ''}` | `/pestitele${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/kosik`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/mapa`; params?: Router.UnknownInputParams; } | { pathname: `/mapa/context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/pestitele`; params?: Router.UnknownInputParams; } | `/pestitele/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/pestitele/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
