/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kosik` | `/kosik`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrace` | `/registrace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pestitele` | `/pestitele`; params?: Router.UnknownInputParams; } | { pathname: `/utils/cartContext`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pestitele/[id]` | `/pestitele/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/kosik` | `/kosik`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/registrace` | `/registrace`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pestitele` | `/pestitele`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/cartContext`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pestitele/[id]` | `/pestitele/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/kosik${`?${string}` | `#${string}` | ''}` | `/kosik${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mapa${`?${string}` | `#${string}` | ''}` | `/mapa${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/registrace${`?${string}` | `#${string}` | ''}` | `/registrace${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pestitele${`?${string}` | `#${string}` | ''}` | `/pestitele${`?${string}` | `#${string}` | ''}` | `/utils/cartContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kosik` | `/kosik`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrace` | `/registrace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pestitele` | `/pestitele`; params?: Router.UnknownInputParams; } | { pathname: `/utils/cartContext`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/pestitele/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/pestitele/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/pestitele/[id]` | `/pestitele/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
